export const START_GETTING_SEARCH_RESULTS = 'START_GETTING_SEARCH_RESULTS'
export const GET_SEARCH_RESULTS_SUCCESS = 'GET_SEARCH_RESULTS_SUCCESS'
export const GET_SEARCH_RESULTS_ERROR = 'GET_SEARCH_RESULTS_ERROR'
