/* Search Results */
export const START_GETTING_SEARCH_RESULTS = 'START_GETTING_SEARCH_RESULTS'
export const GET_SEARCH_RESULTS_SUCCESS = 'GET_SEARCH_RESULTS_SUCCESS'
export const GET_SEARCH_RESULTS_ERROR = 'GET_SEARCH_RESULTS_ERROR'
export const START_CLEANING_SEARCH_RESULTS = 'START_CLEANING_SEARCH_RESULTS'
export const CLEAN_SEARCH_RESULTS_SUCCESS = 'CLEAN_SEARCH_RESULTS_SUCCESS'
export const CLEAN_SEARCH_RESULTS_ERROR = 'CLEAN_SEARCH_RESULTS_ERROR'
/* Cluster */
export const START_GETTING_CLUSTER_INFORMATION = 'START_GETTING_CLUSTER_INFORMATION'
export const GET_CLUSTER_INFORMATION_SUCCESS = 'GET_CLUSTER_INFORMATION_SUCCESS'
export const GET_CLUSTER_INFORMATION_ERROR = 'GET_CLUSTER_INFORMATION_ERROR'
/* Pair */
export const START_GETTING_PAIRS_DETAILS = 'START_GETTING_PAIR_DETAIL'
export const GET_PAIRS_DETAILS_SUCCESS = 'GET_PAIR_DETAIL_SUCCESS'
export const GET_PAIRS_DETAILS_ERROR = 'GET_PAIR_DETAIL_ERROR'
